spring.application.name=smart-campus
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}

# JWT Configuration
app.jwt.secret=MageRahasKeyEkaMeakaThamai2026SmartCampusPAFProject
app.jwt.expiration=86400000

# Frontend URL
app.frontend.url=http://localhost:5173

# CORS Configuration
#app.cors.allowed-origins=http://localhost:5173
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://10.*.*.*:*,http://192.168.*.*:*,http://172.16.*.*:*,http://172.17.*.*:*,http://172.18.*.*:*,http://172.19.*.*:*,http://172.2*.*.*:*,http://172.30.*.*:*,http://172.31.*.*:*

