spring.application.name=smart-campus
spring.data.mongodb.database=smart_campus_db
spring.data.mongodb.uri=${MONGO_URI}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT Configuration
app.jwt.secret=MageRahasKeyEkaMeakaThamai2026SmartCampusPAFProject
app.jwt.expiration=86400000

# Frontend URL (Redirect වෙන්න ඕනේ තැන)
app.frontend.url=http://localhost:5173

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173

# File Upload Configuration (Module C – Ticket Attachments)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
app.uploads.dir=uploads

# Admin registration secret
app.admin.secret=SmartCampus2026Admin